version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  check:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint
          command: yarn lint
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests
          command: |
            npm install -g fern-api
            yarn test --ci
      - run:
          name: Build docker
          command: yarn dockerTagLocal
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff

  generate-sdks:
    docker:
      - image: cimg/node:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install fern
          command: sudo npm install -g fern-api
      - run: |
          export FERN_TOKEN="${FERN_ORG_TOKEN_PROD}"
          git_version="$(scripts/git-version.sh)"
          fern generate --group sdks --log-level debug

  publish:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish fern-postman docker
          command: |
            projectVersion="$(./scripts/git-version.sh)"
            yarn dockerTagVersion "$projectVersion"
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag fern-postman:"$projectVersion" fernapi/fern-postman:"$projectVersion"
            docker push fernapi/fern-postman:"$projectVersion"

workflows:
  version: 2
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - generate-sdks:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          context:
            - fern-tokens
          requires:
            - check
      - publish:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
          requires:
            - check
          context:
            - docker-hub
